version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:v1.14-latest
    restart: always
    volumes:
      - ./envoy/envoy.linux.yaml:/etc/envoy/envoy.yaml
      - ./envoy/certs/domain.crt:/etc/envoy/certs/cert.pem
      - ./envoy/certs/domain.key:/etc/envoy/certs/key.pem
      - ./envoy/certs/myCA.pem:/etc/envoy/certs/ca.pem
    network_mode: "host"