version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:v1.16-latest
    restart: always
    #command: ./docker-entrypoint.sh envoy -l debug -c /etc/envoy/envoy.yaml
    volumes:
      - ./envoy/envoy.mac.yaml:/etc/envoy/envoy.yaml
      - ./envoy/certs/domain.crt:/etc/envoy/certs/cert.pem
      - ./envoy/certs/domain.key:/etc/envoy/certs/key.pem
      - ./envoy/certs/myCA.pem:/etc/envoy/certs/ca.pem
    ports:
      - "443:8443" # entry
      - "9901:9901" # admin
