version: "3.8"

services:
  envoy:
    image: envoyproxy/envoy:v1.14-latest
    restart: always
    volumes:
      - ./envoy/envoy.dev.yaml:/etc/envoy/envoy.yaml
      - ./envoy/certs:/etc/envoy/certs
    network_mode: "host"